from services.open_street_api.TransportMap import TransportMap

def test():
    transport_map = TransportMap("Kadıkoy, Istanbul, Turkey")
    transport_map1 = TransportMap("19 MAYIS MAHALLESİ, Istanbul, Turkey", radius_km=3)
    transport_map.add_search_area_circle()
    transport_map1.add_search_area_circle()
    transport_map.add_transport_stops("bus", "blue", "info-sign")
    transport_map.add_transport_stops("metro", "purple", "info-sign")
    transport_map1.add_transport_stops("bus", "blue", "info-sign")
    transport_map1.add_transport_stops("metro", "purple", "info-sign")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="taxi")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="taxi")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="fast_food")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="fast_food")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="cafe")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="cafe")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="restaurant")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="restaurant")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="college")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="college")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="library")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="library")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="school")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="school")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="university")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="university")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="atm")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="atm")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="hospital")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="hospital")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="arts_centre")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="arts_centre")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="cinema")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="cinema")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="theatre")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="theatre")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="grave_yard")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="grave_yard")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="social_centre")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="social_centre")
    transport_map.add_transport_stops("poi", "green", "info-sign", poi_type="social_facility")
    transport_map1.add_transport_stops("poi", "green", "info-sign", poi_type="social_facility")
    transport_map.merge_map(transport_map1)
    # Save the combined map with all markers and search areas
    transport_map.save_map("last_map.html")
test()